seed: 123
gpus: 8
device: "cuda"
amp: False

# data
dataset: "bcss"
dataset_path: "../data/BCSS_128"  # Path to BCSS 128x128 dataset
split_file: "../data/BCSS_128/BCSS_128.csv"  # CSV file with train/test split
prototype_mask_folder: "../prototype_dict_building_and_coarse_segmentation/output/bcss_30_top:10_0.8_CQ5"  # CQ5 = Cluster Query with n=5 (best quality)
fully_supervised: False

# model
model: "linknet"
pretrain: ""

# train
resume: False
image_size: 
  - 128
  - 128
start_epoch: 0
epochs: 200  # Reduced for smaller dataset
batch_size: 32  # Adjusted for 128x128 images
workers: 4
lr: 1e-3
weight_decay: 1e-5

lr_warmup_epochs: 10
lr_warmup_method: "linear"
lr_warmup_decay: 0.01



# log
print_freq: 10
check_freq: 9999
save_freq: 50  # Save every 50 epochs
output_dir: "./logs/"
description: "bcss_128_refinement"